### ISSUE TITLE
Erreur cuda lors de l’exécution de Detectron

### ISSUE THREAD

**Issue by JulienCheny** [JulienCheny/ImageTagging#1]
Au lancement du programme `infer_simple.py` de detectron, une erreur survient :

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU o
nly mode.
WARNING:root:Debug message: libcuda.so.1: cannot open shared object file: No suc
h file or directory
Found Detectron ops lib: /usr/local/caffe2_build/lib/libcaffe2_detectron_ops_gpu
.so
Traceback (most recent call last):
  File "tools/infer_simple.py", line 49, in <module>
    c2_utils.import_detectron_ops()
  File "/detectron/detectron/utils/c2.py", line 42, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/usr/local/caffe2_build/caffe2/python/dyndep.py", line 50, in InitOpsLib
rary
    _init_impl(name)
  File "/usr/local/caffe2_build/caffe2/python/dyndep.py", line 63, in _init_impl
    ctypes.CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by JulienCheny** [comment]
Solution à essayer : 
Abandonner docker et utiliser directement Anaconda comme dans la vidéo https://www.youtube.com/watch?v=Rgpfk6eYxJA&t=323s. La vidéo présente l'installation de deeplab de TensorFlow.

**Comment by JulienCheny** [comment]
Solution trouvé : utiliser yolo.
